# -*- coding: utf-8 -*-
"""Dp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HVV75_DkYFDUX_cBg3MGZNy0Mw1YUI4

**Data processing using pure python (without libraries)**
"""

import json
def load_data(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
    return data

def display_users(data):
  print("user and there connections ")
  for user in data["users"]:
    print(f"{user['name']} (ID: {user['id']}) - Friends: {user['friends']} - Liked Pages: {user['liked_pages']}")
    print("\n Pages: \n")
  for page in data["pages"]:
    print(f"{page['name']} (ID:{page['id']})")


data = load_data("/content/data_.json")
display_users(data)