# -*- coding: utf-8 -*-
"""Dp2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MbMTq1Zh5sGP91Ohmu5yOtpl4RB-V7Pj
"""

import json
def clean_data(data):
  #remove usersith missing name
  data['users'] = [user for user in data['users']if user['name'].strip()]
  #remove duplicte friends
  for user in data['users']:
    user['friends'] = list(set(user['friends']))
  return data

  #remove inactive users
  data['users'] = [user for user in data['users'] if user['friend'] or
                   user['liked_pages']]

  #remove duplicate pages
  unique_pages = {}
  for page in data["pages"]:
    for page in data['pages']:
      unique_pages[page['id']] = page
  data['pages'] = list(unique_pages.values())
  return data

data = json.load(open("/content/clean_data.json"))
data =clean_data(data)
json.dump(data,open("cleaned_code_data.json","w"),indent = 4)
print("cleaned data saved to cleaned_code_data.json")

